# Generated by Django 3.1.3 on 2023-05-19 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basic_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('poster_src', models.TextField()),
                ('open_date', models.DateField()),
                ('total_score', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='review_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('review_score', models.CharField(max_length=3)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.basic_info')),
            ],
        ),
        migrations.CreateModel(
            name='graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf_idf_word', models.TextField()),
                ('tf_idf_score', models.CharField(max_length=3)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.basic_info')),
            ],
        ),
        migrations.CreateModel(
            name='detail_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synopsis', models.TextField()),
                ('actor', models.TextField()),
                ('netflix_url', models.TextField()),
                ('youtube_url', models.TextField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.basic_info')),
            ],
        ),
    ]
