# Generated by Django 3.1.3 on 2023-05-24 03:08

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_auto_20230524_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_info',
            name='netflix_url',
            field=embed_video.fields.EmbedVideoField(),
        ),
        migrations.AlterField(
            model_name='detail_info',
            name='youtube_url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
