# Generated by Django 3.1.3 on 2023-05-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_auto_20230524_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_info',
            name='poster_src',
            field=models.ImageField(blank=True, null=True, upload_to='pybo'),
        ),
    ]
