# Generated by Django 3.1.3 on 2023-05-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_auto_20230524_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_info',
            name='total_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='graph',
            name='tf_idf_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review_info',
            name='review_score',
            field=models.IntegerField(),
        ),
    ]
