# Generated by Django 3.1.3 on 2023-06-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_auto_20230607_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_info',
            name='review',
        ),
        migrations.AddField(
            model_name='review_info',
            name='review1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review_info',
            name='review2',
            field=models.TextField(null=True),
        ),
    ]
