# Generated by Django 3.1.3 on 2023-06-08 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_auto_20230607_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_info',
            old_name='review1',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='review_info',
            name='review2',
        ),
    ]
